### ISSUE TITLE
Error "expected newly cut file to have sequence:offset"

### ISSUE THREAD

**Issue by replay** [grafana/mimir-prometheus#134]
We have seen multiple Mimir instances panic with the error "expected newly cut file to have sequence:offset".

This error happens under the following conditions:
When the `chunkDiskMapper` writes a chunk through the queue it decides whether a new file needs to be cut. If so, then it predicts what the sequence ID of that next file is going to be, based on the files which it is aware of. It then adds a job to the queue which indicates that a new file needs to be cut and what the next expected sequence ID is. When the worker processes the job it cuts a new file and picks the next sequence ID based on the files which are present in the file system, then it compares whether the resulting ID matches the expected sequence ID.

It is also important to point at that in all cases where we saw the error the expected ID was some number `>1` while the real sequence ID which resulting from cutting a new file was `1`, this indicates that the chunkDiskMapper was under the impression that some chunk files exist in the file system, but once it cut a new file it did not see any files, resulting in the next ID being `1`. These are the logs:

```
  |   | 2022-02-10 11:04:23 | panic: expected newly cut file to have sequence:offset 11:8, got 1:8
  |   | 2022-02-10 11:02:32 | panic: expected newly cut file to have sequence:offset 327:8, got 1:8
  |   | 2022-02-10 11:01:29 | panic: expected newly cut file to have sequence:offset 365:8, got 1:8
  |   | 2022-02-10 11:01:29 | panic: expected newly cut file to have sequence:offset 531:8, got 1:8
  |   | 2022-02-10 11:00:50 | panic: expected newly cut file to have sequence:offset 509:8, got 1:8
  |   | 2022-02-10 11:00:50 | panic: expected newly cut file to have sequence:offset 509:8, got 1:8
  |   | 2022-02-10 11:00:34 | panic: expected newly cut file to have sequence:offset 116:8, got 1:8
  |   | 2022-02-10 11:00:21 | panic: expected newly cut file to have sequence:offset 253:8, got 1:8
  |   | 2022-02-10 11:00:21 | panic: expected newly cut file to have sequence:offset 253:8, got 1:8
  |   | 2022-02-10 11:00:18 | panic: expected newly cut file to have sequence:offset 422:8, got 1:8
  |   | 2022-02-10 11:00:17 | panic: expected newly cut file to have sequence:offset 365:8, got 1:8
  |   | 2022-02-10 11:00:13 | panic: expected newly cut file to have sequence:offset 397:8, got 1:8
  |   | 2022-02-10 11:00:11 | panic: expected newly cut file to have sequence:offset 951:8, got 1:8
  |   | 2022-02-10 11:00:07 | panic: expected newly cut file to have sequence:offset 872:8, got 1:8
  |   | 2022-02-10 10:57:04 | panic: expected newly cut file to have sequence:offset 81:8, got 1:8
  |   | 2022-02-10 10:35:08 | panic: expected newly cut file to have sequence:offset 5:8, got 1:8
  |   | 2022-02-10 10:35:08 | panic: expected newly cut file to have sequence:offset 37:8, got 1:8
  |   | 2022-02-10 10:00:04 | panic: expected newly cut file to have sequence:offset 16:8, got 1:8
  |   | 2022-02-10 10:00:00 | panic: expected newly cut file to have sequence:offset 17:8, got 1:8
  |   | 2022-02-10 08:28:26 | panic: expected newly cut file to have sequence:offset 34:8, got 1:8
```

**Comment by codesome** [comment]
I think the fix has been vendored here. Closing.
