### ISSUE TITLE
Ignore unknown chunk encodings when replaying m-map chunks on startup

### ISSUE THREAD

**Issue by codesome** [grafana/mimir-prometheus#191]
The out-of-order support is going to introduce a new encoding type for m-map chunks (just to identify ooo chunks, while it will still be XOR encoded). If we choose to rollback for whatever reason, we must be able to ignore this new encoding to make the rollback successful without data loss.

Hence we must add the support to ignore unknown chunk encodings during replay _now_ so that we can save time rolling out out-of-order support (which will require the fix to this issue to be already rolled out).

cc @jesusvazquez @Dieterbe

**Comment by jesusvazquez** [comment]
Done in https://github.com/grafana/mimir-prometheus/pull/196
