### ISSUE TITLE
Rename OutOfOrderAllowance to OutOfOrderTimeWindow

### ISSUE THREAD

**Issue by codesome** [grafana/mimir-prometheus#274]
This was suggested in Mimir and the change has been done there. We need to do it here as well. I am opening this issue to keep track of it. The change should also be done for the flag.

cc @jesusvazquez

**Comment by jesusvazquez** [comment]
Related https://github.com/grafana/mimir-prometheus/pull/276

**Comment by pracucci** [comment]
Is this issue closed by https://github.com/grafana/mimir-prometheus/pull/276?

**Comment by jesusvazquez** [comment]
Yes it is. Closing
