### ISSUE TITLE
Simplify the concept of `OutOfOrderTimeWindow`

### ISSUE THREAD

**Issue by codesome** [grafana/mimir-prometheus#284]
## Problem

Currently, here is how the `OutOfOrderTimeWindow` is interpreted when there is a matching time series or not.

Taking example of `OutOfOrderTimeWindow`

**Case 1**: *If there is a series in the Head block for the sample*, whose max time is let's say `SeriesMaxT`, then we accept out-of-order samples for this series that has timestamp greater than or equal to `SeriesMaxT-OutOfOrderTimeWindow`, no other logic.

**Case 2**: *If a sample does not have any series in the Head block*, we don't have a `SeriesMaxT` to compare with. So we take the Head's maxt (call it `HeadMaxT`). So the ingestable window for the "out-of-order" sample becomes `HeadMaxT-OutOfOrderTimeWindow`. There is another caveat here, more like 2 sub-cases

  * Case 2.1: If the sample timestamp was after `HeadMaxT-1h`, it is still ingestable as an in-order sample. And it goes in the in-order Head. Hence if `OutOfOrderTimeWindow` was less than 1h, it technically has no use if the series does not exist.
  * Case 2.1: If the sample timestamp was before `HeadMaxT-1h`, it cannot go in the in-order Head. Only then the `HeadMaxT-OutOfOrderTimeWindow` is applicable, and only makes sense if `OutOfOrderTimeWindow` was greater than 1h.

Now here is one example of irregularity/confusion with having these 2 cases. 

`OutOfOrderTimeWindow=30m`. Let's say currently `HeadMaxT=10h`. And there is an incoming sample with `T=8h40m`, and the sample has no series in the Head.

Now this sample will be rejected because it doesn't fit in both `T >= HeadMaxT-1h` and `T >= HeadMaxT-OutOfOrderTimeWindow` according to the case 2 above.

BUT, if by chance there was a sample for that series that came right before with `T2=9h1m`, then it would go in the in-order Head and make `SeriesMaxT=9h1m`. And since the case 1 applies now, the earlier sample of `T=8h40m` is suddenly acceptable.

## Proposal

An updated version of **case 2**.

If the series does not exist, then it is same as case 2 above. If the series exist, and if the sample is out of order, then we check if the sample timestamp is after `HeadMaxT-OutOfOrderTimeWindow`, hence removing `SeriesMaxT` completely out of the picture.

This takes the definition of `OutOfOrderTimeWindow` to be "how old a sample can be to be accepted as an out-of-order sample". And the "old" is calculated from the latest timestamp of the TSDB.

Reason 1: Simpler to reason about IMO.

Reason 2: Only having the modified case 2 is more restrictive. So, it is easier to go from more restrictive to less restrictive without breaking users if we choose to add case 1 in the future. The other way round might break users (from case1+2 to just case 2, if folks start depending on case 1).

---

cc @jesusvazquez @pstibrany @pracucci @bboreham for your thoughts

**Comment by jesusvazquez** [comment]
Just hoping by to say that `removing SeriesMaxT completely out of the picture.` completely makes sense to me. When I was explaining how this worked the other day it felt so odd. Just thinking in terms of head maxt simplifies the entire conversation.

**Comment by pracucci** [comment]
Is my understanding correct that you want to change the case 1, always comparing the incoming sample timestamp with the head max time? If so, then makes sense to me.

**Comment by jesusvazquez** [comment]
> Is my understanding correct that you want to change the case 1, always comparing the incoming sample timestamp with the head max time? If so, then makes sense to me.

Yes that is correct.

> Can we close this issue because done by https://github.com/grafana/mimir-prometheus/pull/285?

Yes, I believe we can, I'm going to go ahead and do it. @codesome if you think there is something else please reopen.

**Comment by pstibrany** [comment]
Does this mean that `OutOfOrderTimeWindow` has no meaning after this change, if is is less than 1h?

**Comment by codesome** [comment]
@pstibrany I don't think I understand. Samples can still come as out-of-order if their timestamp is even a minute old. So `OutOfOrderTimeWindow` makes sense for any value, including less than 1h.

**Comment by pstibrany** [comment]
> Does this mean that `OutOfOrderTimeWindow` has no meaning after this change, if is is less than 1h? (ie. sample will still be in-order)

I think not... `out_of_order_time_window: '30m',` allows us to accept samples in `[T-30m, T)` for "T=max T for series."
