### ISSUE TITLE
Optionally do not merge out-of-order chunks with in-order chunks in ChunkQuerier

### ISSUE THREAD

**Issue by codesome** [grafana/mimir-prometheus#298]
Currently with the out-of-order feature, when there are overlaps in the ingester, (among blocks or the out of order part of head block with the in-order part or other block), we tend to merge overlapping chunks before sending it to the querier from the ingesters.

Mimir seems to handle unsorted overlapping chunks since it has to handle the dedupe of replication anyway. So we can skip the merging of chunks in ingesters and save some CPU. This needs to be an opt-in and not default, since the upstream Prometheus will prefer/require merging them.

cc @jesusvazquez
cc @pracucci @pstibrany to verify my comment about Mimir handling unsorted overlapping chunks.

**Comment by pstibrany** [comment]
> cc @pracucci @pstibrany to verify my comment about Mimir handling unsorted overlapping chunks.

Yes, Mimir will handle unsorted overlapping chunks.

Mimir's querier already gets overlapping chunks from multiple ingesters, and when it's going to merge them, it first puts them into unsorted slice of chunks (in `mergeSeriesSets`). Sorting and merging chunks for given series is then done by `chunkIteratorFunc` and various implementations handle it differently (`mergeChunks` extracts all samples first, and does merging of samples, `batch.NewChunkMergeIterator` and `iterators.NewChunkMergeIterator` sort chunks by their `MinTime` or `From` first and then merge).

**Comment by codesome** [comment]
Adding the support here https://github.com/grafana/mimir-prometheus/pull/299/
